languages:
  - javascript
  - jsx
  - css
files:
  - "src/server/**/*.js"
  - "src/client/**/*.js"
  - "src/client/components/styles/*.css"
exclude:
  - "src/server/public/js/bundle.js"
  - "src/server/public/js/bundle.js.map"
  - "node_modules/**"
  - "src/**/*.spec.js"
  - "config/**"
  - "fixtures/**"
reporter: json
