language: python
python:
- '2.7'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
matrix:
  fast_finish: true
script:
  - pushd light-controller
  - pip install -r requirements.txt
  - pushd fixtures
  - python run.py &
  - make test
  - popd
  - popd
  - pushd web-controller
  - nvm install v6
  - npm install
  - npm test
  - popd
