language: python
python:
- '2.7'
script:
  - pushd light-controller
  - pip install -r requirements.txt
  - pushd fixtures
  - python run.py &
  - popd
  - make test
  - popd
  - pushd web-controller
  - nvm install v6
  - npm install
  - npm test
  - popd
